version: "3.7"
services: 
  backend: 
    build: ./backend
    container_name: backend
    ports:
      - 4001:4001
    volumes:
      - ./db:/app/db
    networks:
      leaderboard_network:
        aliases:
          - leaderboard

networks:
  leaderboard_network:
    name: leaderboard_network

volumes:
  db_data:
    driver: local
    name: db_data