version: "3.7"
services:
  db:
    build: ./db
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leaderboard
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      leaderboard_network:
        aliases:
          - leaderboard
  
  backend: 
    build: ./backend
    container_name: backend
    ports:
      - 4001:4001
    depends_on:
      - db
    networks:
      leaderboard_network:
        aliases:
          - leaderboard
    environment:
      LEADERBOARD_DB_HOST: db
      LEADERBOARD_DB_PORT: 3306
      LEADERBOARD_DB_USER: leaderboard
      LEADERBOARD_DB_PASSWORD: AVeryComplicatedPassword
      LEADERBOARD_DB_NAME: leaderboard

networks:
  leaderboard_network:
    name: leaderboard_network

volumes:
  db_data:
    driver: local
    name: db_data