# Generated by Django 5.1.2 on 2024-11-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teams",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
